// Problem 2 - Even Fibonacci numbers

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int sum;
int placeOne;
int placeTwo;
int placeThree;

int main()
{
	placeOne = 1;
	placeTwo = 2;
	sum = 2;
	do
	{
		placeThree = placeOne + placeTwo;
		if (placeThree % 2 == 0)
		{
			sum = sum + placeThree;
		}
		placeOne = placeTwo;
		placeTwo = placeThree;
	} while (placeThree < 4000000);

	cout << sum << endl;

	return 0;
}
